# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TodoListApp_Realm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoListApp_Realm
pod 'RealmSwift'
pod 'SwipeCellKit'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

end
